version: "3.8"
services:
  database-prod:
    container_name: database-prod
    image: "mysql"
    volumes:
      - database-prod-data:/var/lib/mysql
    env_file:
      - ./env/prod.env
    ports:
      - "3306:3306"
    networks:
      - network-prod
  backend-prod:
    container_name: backend-prod
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-prod
    env_file:
      - ./env/prod.env
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - database-prod
    networks:
      - network-prod

volumes:
  database-prod-data:

networks:
  network-prod:
    driver: bridge